
speech_config:
  mel_layer_type: Melspectrogram #Spectrogram/Melspectrogram/leaf
  mel_layer_trainable: False #leaf support train
  add_wav_info: False
  sample_rate: 16000
  frame_ms: 25
  stride_ms: 10
  num_feature_bins: 80
  reduction_factor: 4 #should keep the same with model_config, DS2 : time_reduction_factor *= s[0] for s in 'conv_strides'
  train_list: './test_list.txt'
  eval_list: './test_list.txt'
  wav_max_duration: 7 # s
  only_chinese: True
  streaming: True
  streaming_bucket: 0.16 #s
  pinyin_map: './asr/configs/dict/pinyin2phone.map'
  extra_txt_list: ""



inp_config:
  vocabulary: './asr/configs/dict/pinyin.txt'
  blank_at_zero: False
  beam_width: 1
tar_config:
  vocabulary: './asr/configs/dict/lm_tokens.txt'
  blank_at_zero: False
  beam_width: 1

augments_config:
  aug_ratio: 0.5
  noise:
    active: False
    sample_rate: 16000
    SNR: [0,15]
    noises: './noise'
  masking:
    active: False
    zone: (0.1,0.9)
    mask_ratio: 0.3
    mask_with_noise: False

  pitch:
    active: False
    zone: (0.0,1.0)
    sample_rate: 16000
    factor: (-1,3)

  speed:
    active: False
    factor: (0.9,1.2)

  rir:
    active: False       # 请确保rir_generator 已经安装
    sample_rate: 16000

  hz:
    active: False

  vc:
    active: False #设置True的时候，请确保vc_aug_model_L.onnx下载并放置于TensorflowASR/augmentations/tts_for_asr/models 目录下。

  spec_aug:
    active: True
    window: 10
    ratio: 0.5

optimizer_config:
  lr: 0.0001
  warmup_steps: 10000
  beta1: 0.9
  beta2: 0.98
  epsilon: 0.000001

running_config:
  batch_size: 32
  num_epochs: 1000
  outdir: './chunk_conformer-logs'
  log_interval_steps: 300
  eval_interval_steps: 500
  save_interval_steps: 500

